///|
pub type Vec2 = @math.Vec2

///|
pub type Rect = @math.Rect

///|
pub type Color = @color.Color

///|
pub type DrawCmd = @draw.DrawCmd

///|
pub type DrawList = @draw.DrawList

///|
pub type Id = @core.Id

///|
pub type IdStack = @core.IdStack

///|
pub type RawInput = @core.RawInput

///|
pub type InputState = @core.InputState

///|
pub type Response = @core.Response

///|
pub type UIContext = @core.UIContext
